/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista_Libro_Contable;


import ModeloDAO.CuentaDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Adrian
 */
public class Frm_Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form LibroContable
     */
    public Frm_Cuenta()  {
        initComponents();
        setTitle("Cuentas Contables");
         setLocationRelativeTo(null);
         setExtendedState(Frm_Cuenta.MAXIMIZED_BOTH);
         //Cuenta.MostrarListaDeCuenta();
         
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btbVolverMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCuentas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCuenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoCuenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTipoCuenta = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtSaldo_Inicial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btbAgregarCuenta = new javax.swing.JButton();
        FondoCompleto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de inventario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cuentas Contables");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        btbVolverMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Atras.png"))); // NOI18N
        btbVolverMenu.setText("Volver");
        btbVolverMenu.setToolTipText("");
        btbVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbVolverMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btbVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 140, 40));

        TablaCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaCuentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 1310, 240));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, 30));

        txtNombreCuenta.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtNombreCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNombreCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 220, 30));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Códico :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        txtCodigoCuenta.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCodigoCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCodigoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 220, 30));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo Cuenta :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jComboBoxTipoCuenta.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jComboBoxTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "PASIVO", "PATRIMONIO", "INGRESO", "GASTO" }));
        jPanel1.add(jComboBoxTipoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 150, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/billete-de-banco.png"))); // NOI18N
        jLabel6.setText("Saldo Inicial :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        txtSaldo_Inicial.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtSaldo_Inicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtSaldo_Inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 232, 150, 30));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descripción :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, -1, -1));

        txtDescripcion.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, 210, 30));

        btbAgregarCuenta.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbAgregarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cuenta-bancaria.png"))); // NOI18N
        btbAgregarCuenta.setText("Agregar");
        jPanel1.add(btbAgregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 660, 150, -1));

        FondoCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(FondoCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1380, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 742));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbVolverMenuActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_btbVolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
  
  ModeloDAO.CuentaDao Cuenta = new CuentaDao();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoCompleto;
    public static javax.swing.JTable TablaCuentas;
    public static javax.swing.JButton btbAgregarCuenta;
    public static javax.swing.JButton btbVolverMenu;
    public static javax.swing.JComboBox<String> jComboBoxTipoCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtCodigoCuenta;
    public static javax.swing.JTextField txtDescripcion;
    public static javax.swing.JTextField txtNombreCuenta;
    public static javax.swing.JTextField txtSaldo_Inicial;
    // End of variables declaration//GEN-END:variables
}
