/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_Gestionar_Proveedor;

import Modelo.cuenta;

/**
 *
 * @author avila
 */
public class Vista_Pagar_Compra extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_Pagar_Compra.class.getName());

    /**
     * Creates new form Vista_Pagar_Compra
     */
    public Vista_Pagar_Compra() {
        initComponents();
        setTitle("Pagar Compra");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btbVolveMenu = new javax.swing.JButton();
        btbAsumirPago = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPagarDeudas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxFormaPago = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxCuenta = new javax.swing.JComboBox<>();
        btbAbonar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtABono = new javax.swing.JTextField();
        btbPagar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxCuentaDestino = new javax.swing.JComboBox<>();
        Fondo_Pantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pagar Compras");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de inventario");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        btbVolveMenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbVolveMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casita.png"))); // NOI18N
        btbVolveMenu.setText("Volver ");
        jPanel1.add(btbVolveMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, -1, 40));

        btbAsumirPago.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbAsumirPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/billete-de-banco.png"))); // NOI18N
        btbAsumirPago.setText("Asumir Pago");
        jPanel1.add(btbAsumirPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, 210, 40));

        TablaPagarDeudas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaPagarDeudas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 1290, 230));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("# Factura :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, 30));

        txtNumeroFactura.setEditable(false);
        txtNumeroFactura.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtNumeroFactura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNumeroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 120, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Forma de Pago :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jComboBoxFormaPago.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jComboBoxFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transferencia", "Dolar", "Credito" }));
        jPanel1.add(jComboBoxFormaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 200, 30));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CUENTA ORIGEN :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 30));

        jComboBoxCuenta.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jPanel1.add(jComboBoxCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 370, 30));

        btbAbonar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbAbonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Abono.png"))); // NOI18N
        btbAbonar.setText("Abonar");
        jPanel1.add(btbAbonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 150, 40));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Abono Inicial :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, -1, 30));

        txtABono.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        txtABono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtABono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, 120, 30));

        btbPagar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btbPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/billete-de-banco.png"))); // NOI18N
        btbPagar.setText("Pagar");
        jPanel1.add(btbPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 663, 150, 40));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CUENTA DESTINO :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

        jComboBoxCuentaDestino.setFont(new java.awt.Font("Georgia", 0, 10)); // NOI18N
        jComboBoxCuentaDestino.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.add(jComboBoxCuentaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, 370, 30));

        Fondo_Pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoMordeno.jpg"))); // NOI18N
        jPanel1.add(Fondo_Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 1370, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1369, 741));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo_Pantalla;
    public static javax.swing.JTable TablaPagarDeudas;
    public static javax.swing.JButton btbAbonar;
    public static javax.swing.JButton btbAsumirPago;
    public static javax.swing.JButton btbPagar;
    public static javax.swing.JButton btbVolveMenu;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuenta;
    public static javax.swing.JComboBox<cuenta> jComboBoxCuentaDestino;
    public static javax.swing.JComboBox<String> jComboBoxFormaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtABono;
    public static javax.swing.JTextField txtNumeroFactura;
    // End of variables declaration//GEN-END:variables
}
